# Generated by Django 4.1.3 on 2022-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAlumno', models.CharField(max_length=6)),
                ('nombreApellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('anioNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=10)),
                ('nombreCurso', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('numCreditos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDocente', models.CharField(max_length=6)),
                ('nombreApellido', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('anioNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('aula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSemestre', models.CharField(max_length=6)),
                ('anio', models.IntegerField()),
                ('periodoSemestre', models.CharField(max_length=1)),
            ],
        ),
    ]
