# Generated by Django 4.1.3 on 2022-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='codAlumno',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idCurso',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='codDocente',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='idSemestre',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
