# Generated by Django 4.1.3 on 2022-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0002_remove_alumno_id_remove_curso_id_remove_docente_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='anioNacimiento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
