# Generated by Django 4.1.3 on 2022-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0003_alter_alumno_anionacimiento_alter_alumno_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='tipo',
            field=models.CharField(choices=[('C', 'Contratado'), ('N', 'Nombrado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('M', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=10),
        ),
    ]
