# Generated by Django 4.1.3 on 2022-11-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0004_alter_docente_tipo_alter_horario_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoOfrecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaMatriculas.docente')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaMatriculas.curso')),
                ('idSemestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaMatriculas.semestre')),
            ],
        ),
    ]
