# Generated by Django 4.1.3 on 2022-11-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0005_cursoofrecido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CursoOfrecido',
            new_name='CursosOfrecido',
        ),
    ]
