# Generated by Django 4.1.3 on 2022-11-13 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaMatriculas', '0006_rename_cursoofrecido_cursosofrecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Regular'), ('T', 'Tricada')], max_length=1)),
                ('codAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaMatriculas.alumno')),
                ('idCursoOfrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaMatriculas.cursosofrecido')),
            ],
        ),
    ]
